name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        cfg:
          - os: ubuntu-latest
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/test_env.yaml
          create-args: python=${{ matrix.python-version }}

      - name: Install package
        run: python -m pip install -e .

      - name: Test the package
        run: pytest -v openff/
