name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
        cfg:
          - os: ubuntu-latest
          - os: macOS-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          # More info on options: https://github.com/conda-incubator/setup-miniconda
          python-version: ${{ matrix.python-version }}
          environment-file: devtools/conda-envs/test_env.yaml
          channels: conda-forge,defaults,omnia
          activate-environment: test
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install -e .
          conda list
          conda info --all

      - name: Test the package
        shell: bash -l {0}
        run: |
          pytest -v openff/
